#!/usr/bin/env bash

if [ -z "$1" ]
then
    venv=".venv"
else
    venv="$1"
fi


if [ ! -d "$venv" ]; then
    echo "[+] Creating virtual environment: ${venv}"
    python -m venv "$venv"
fi


echo "[+] Activating virtual environment: ${venv}"


if [ -d "${venv}/Scripts" ]; then
    source "${venv}/Scripts/activate"
else
    source "${venv}/bin/activate"
fi
