version: '3'

services:
  lobe-chat:
    image: lobehub/lobe-chat
    ports:
      - 3210:3210
    environment:
      - OPENAI_API_KEY=KKK
      - OPENAI_PROXY_URL=https://aaa.openai.azure.com
      - ACCESS_CODE=One2Three