name: CI

on:
    workflow_dispatch:
    pull_request:
        branches: [main]

jobs:
    test:
        name: "Test"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # - name: Set up Python
            #   uses: actions/setup-python@v2
            #   with:
            #       python-version: "3.12"

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  enable-cache: true
                  cache-dependency-glob: uv.lock

            - name: Set up Python
              run: uv python install 3.12

            # - name: Install dependencies
            #   run: |
            #       poetry install

            # - name: Lint with ruff
            #   run: |
            #       poetry run ruff check .

            # - name: Run tests with pytest
            #   run: |
            #       poetry run pytest

            # - name: Build
            #   run: poetry build

            - name: Build
              run: uv build

    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  enable-cache: true
                  cache-dependency-glob: uv.lock

            - name: Set up Python
              run: uv python install 3.12

            # - name: Publish
            #   run: uv publish -t ${{ secrets.PYPI_TOKEN }}
