name: PR Gate

on:
    workflow_dispatch:
    pull_request:
        branches: [main]

jobs:
    pr-gate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  poetry install

            - name: Lint with ruff
              run: |
                  poetry run ruff check .

            - name: Run tests with pytest
              run: |
                  poetry run pytest

            - name: Build
              run: poetry build
