name: PR Gate

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-gate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
    - name: Lint with ruff
      run: ruff .
    - name: Run tests with pytest
      run: pytest
